src/Entity/Demandes.php
<?php

namespace App\Entity;

use App\Repository\DemandesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DemandesRepository::class)]
class Demandes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $Civilite = null;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    #[ORM\Column(length: 255)]
    private ?string $Structure = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $NomStructure = null;

    #[ORM\Column(length: 255)]
    private ?string $Formule = null;

    #[ORM\Column(length: 255)]
    private ?string $Montant = null;

    #[ORM\Column(length: 255)]
    private ?string $DateCreation = null;

    #[ORM\Column(length: 255)]
    private ?string $DelaiCreation = null;

    #[ORM\Column(length: 255)]
    private ?string $TypeEntreprise = null;

    #[ORM\Column(length: 255)]
    private ?string $TypeAbonnement = null;

    #[ORM\Column(length: 255)]
    private ?string $EntrepriseOrCompta = null;

    #[ORM\Column(length: 255)]
    private ?string $Status = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Mobile = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->Civilite;
    }

    public function setCivilite(string $Civilite): self
    {
        $this->Civilite = $Civilite;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getStructure(): ?string
    {
        return $this->Structure;
    }

    public function setStructure(string $Structure): self
    {
        $this->Structure = $Structure;

        return $this;
    }

    public function getNomStructure(): ?string
    {
        return $this->NomStructure;
    }

    public function setNomStructure(?string $NomStructure): self
    {
        $this->NomStructure = $NomStructure;

        return $this;
    }

    public function getFormule(): ?string
    {
        return $this->Formule;
    }

    public function setFormule(string $Formule): self
    {
        $this->Formule = $Formule;

        return $this;
    }

    public function getMontant(): ?string
    {
        return $this->Montant;
    }

    public function setMontant(string $Montant): self
    {
        $this->Montant = $Montant;

        return $this;
    }

    public function getDateCreation(): ?string
    {
        return $this->DateCreation;
    }

    public function setDateCreation(string $DateCreation): self
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }

    public function getDelaiCreation(): ?string
    {
        return $this->DelaiCreation;
    }

    public function setDelaiCreation(string $DelaiCreation): self
    {
        $this->DelaiCreation = $DelaiCreation;

        return $this;
    }

    public function getTypeEntreprise(): ?string
    {
        return $this->TypeEntreprise;
    }

    public function setTypeEntreprise(string $TypeEntreprise): self
    {
        $this->TypeEntreprise = $TypeEntreprise;

        return $this;
    }

    public function getTypeAbonnement(): ?string
    {
        return $this->TypeAbonnement;
    }

    public function setTypeAbonnement(string $TypeAbonnement): self
    {
        $this->TypeAbonnement = $TypeAbonnement;

        return $this;
    }

    public function getEntrepriseOrCompta(): ?string
    {
        return $this->EntrepriseOrCompta;
    }

    public function setEntrepriseOrCompta(string $EntrepriseOrCompta): self
    {
        $this->EntrepriseOrCompta = $EntrepriseOrCompta;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->Status;
    }

    public function setStatus(string $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->Mobile;
    }

    public function setMobile(?string $Mobile): self
    {
        $this->Mobile = $Mobile;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Entity\Demandes;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class DashboardController extends AbstractController
{
 
    #[Route('/dashboard', name: 'app_dashboard')]
    public function test(ManagerRegistry $doctrine, Request $request, AuthenticationUtils $auth): Response
    {
        $orm = $doctrine->getManager();

        $session = $request->getSession();

        $authed = $session->get('auth');

        // if ( $authed != 1) {
        //     return $this->redirect("/login");
        // }

        $demandes_entreprise = $orm->getRepository(Demandes::class)->findBy(
            [
                "EntrepriseOrCompta" => 1 // Entreprise
            ]
        );

        $demandes_compta = $orm->getRepository(Demandes::class)->findBy(
            [
                "EntrepriseOrCompta" => 2 // Comptabilite
            ]
        );

        return $this->render('dashboard/dashboard.html.twig', [
            'entreprise' => array_reverse($demandes_entreprise),
            'comptabilite' => array_reverse($demandes_compta),
            'count_entreprise' => count($demandes_entreprise),
            'count_comptabilite' => count($demandes_compta),
            'user' => $auth->getLastUsername()
        ]);
    }

    #[Route('/dashboard/consultion-demandes-{id}', name: 'app_demandes_view')]
    public function index( int $id, ManagerRegistry $doctrine, Request $request, AuthenticationUtils $auth): Response
    {

        $orm = $doctrine->getManager();

        if ( !$id) die('Access refused');

            $demandes= $orm->getRepository(Demandes::class)->findBy(
                [
                    "id" => $id
                ]
            );

        if ( count($demandes) != 1) die('Access refused');
      
        // dd($demandes);
        
         return $this->render('dashboard/demandes.html.twig', [
            'demandes' => $demandes[0],
            'user' => $auth->getLastUsername()
        ]);


    }

    #[Route('/dashboard/demandes-type-{type}', name: 'app_demandes_all')]
    public function demandes( int $type, ManagerRegistry $doctrine, Request $request, AuthenticationUtils $auth): Response
    {

        $orm = $doctrine->getManager();

        if ( !$type) die('Access refused');

        $demandes = $orm->getRepository(Demandes::class)->findBy(
            [
                "EntrepriseOrCompta" => $type // Entreprise
            ]
        );

        $demandes = $orm->getRepository(Demandes::class)->findBy(
            [
                "EntrepriseOrCompta" => $type // Comptabilite
            ]
        );
     
        // dd($demandes);
        
         return $this->render('dashboard/liste.html.twig', [
            'demandes' => array_reverse($demandes),
            'type' => $type,
            'user' => $auth->getLastUsername()
        ]);


    }


    #[Route('/dashboard/create-blog', name: 'app_create_blog')]
    public function create_blog( AuthenticationUtils $auth): Response
    {
            
        return $this->render('dashboard/blog_create.html.twig',['user' => $auth->getLastUsername()]);

    }

    #[Route('/dashboard/admin-blog/edit/{id}', name: 'app_edit_blog')]
    public function admin_edit_blog(EntityManagerInterface $em,string $id, AuthenticationUtils $auth): Response
    {

        $blog = $em->getRepository(Blog::class)->find($id);

        return $this->render('dashboard/blog_edit.html.twig',['user' => $auth->getLastUsername() , 'blog' => $blog]);

    }

    #[Route('/dashboard/admin-blog/delete/{id}', name: 'app_delete_blog')]
    public function admin_delete_blog(EntityManagerInterface $em,string $id, AuthenticationUtils $auth): Response
    {

        $blog = $em->getRepository(Blog::class)->find($id);

        $em->remove($blog);

        $em->flush();

        return $this->redirectToRoute('app_mes_blogs');

    }

    #[Route('/get/blog', name: 'app_get_blog', methods:['POST'])]
    public function admin_get_blog(EntityManagerInterface $em,Request $request): Response
    {
        $data = json_decode($request->getContent(), false);

        $blog = $em->getRepository(Blog::class)->find($data->id);

        return $this->json([
            'code' => 'success',
            'message' => $blog
        ]);

    }

    #[Route('/dashboard/mes-blogs', name: 'app_mes_blogs')]
    public function mes_blogs(EntityManagerInterface $em, AuthenticationUtils $auth): Response
    {

        $blog = $em->getRepository(Blog::class)->findAll();

        return $this->render('dashboard/_blog_list.html.twig', [
            'blogs' => array_reverse($blog),
            'total' => count( $blog),
            'user' => $auth->getLastUsername()
        ]);
    }

    #[Route('/post/blog', name: 'app_post_blog', methods: ["POST"])]
    public function post_blog(Request $request , EntityManagerInterface $em): Response
    {            
        $data = $request->request->all(); // POST DATA
        $image = $request->files->get('image'); // GET FILE

        if ( !isset( $data['id'])) {
            $blog = new Blog();
        } else {
            $blog = $em->getRepository(Blog::class)->find( $data['id']);
        }
        
        $blog->setTitre( $data['title']);
        $blog->setContenu( $data['contenu']);
        $blog->setDescription( $data['description']);
        $blog->setPublication( date('d/m/Y'));

    
        if ( !$image && $blog->getImage()) {
            // No image received but image exists in DB
        } else {

            if ( !$image) return $this->json(['code' => 'error', 'message' => 'Image obligatoire']);

            $filename = md5(uniqid()) . '.' . $image->guessExtension();
            $image->move($this->getParameter('image_directory'), $filename);

            $blog->setImage( $filename );
        }    

        if ( !isset( $data['id'])) {
            $em->persist($blog);
        } 
        
        $em->flush();

        return $this->json(['code' => 'success' , 'message' => 'blog posted']);

    }

    #[Route('/reponse-client', name: 'app_reponse_jvgo', methods: ["POST"])]
    public function reponse_client(Request $request, ManagerRegistry $doctrine, MailerInterface $mailer): Response
    {
        $data = json_decode($request->getContent(), false);

        if ($data) {

            $orm = $doctrine->getManager();

            $demande = $orm->getRepository(Demandes::class)->find($data->id);

            if (!$demande) return $this->json(['code' => 'error', 'message' => 'id manquant']);

            $demande->setStatus('Repondu');

            $orm->flush();

            $jvgo = $this->getParameter('app.admin_mail');

            try {
                $email = (new Email())
                    ->from($jvgo)
                    ->to($data->email)
                    ->priority(Email::PRIORITY_HIGH)
                    ->subject("JVGO Reponse !")
                    ->html("Bonjour ! <br>{$data->message} ");

                $mailer->send($email);
            } catch (\Throwable $th) {
                $errorOrSuccess =  $th;
            }

            return $this->json([
                'code' => 'success',
                'message' => 'Reponse transmit'
            ]);
        } else {

            return $this->json([
                'code' => 'error',
                'message' => 'data-raw body vide'
            ]);
        }
    }
}

templates/dashboard/_blog_list.html.twig
{% extends "dashboard/_base.html.twig" %}

{% block injectedPage %}

	<!-- start page title -->
	<div class="row">
		<div class="col-12">
			<div class="page-title-box d-flex align-items-center justify-content-between">
				<h4 class="page-title mb-0 font-size-18">Mes blogs</h4>
			</div>
		</div>
	</div>

    <div class="row">

		<div class="col-xl-12">
	
				<div class="card">
					<div class="card-body">
						<h4 class="card-title mb-4">Mes Blogs ( {{total }} )</h4>

						<div class="table-responsive">
							<table class="table table-centered">
								<thead>
									<tr>
										<th scope="col">No.</th>
										<th scope="col">Titre</th>
										<th scope="col" colspan="2">description</th>
										<th scope="col">Publie le</th>
                                        <th scope="col">Voir</th>
										<th scope="col">supprimer</th>
									</tr>
								</thead>
								<tbody>
									{% for blog in blogs %}
										<tr>
											<td>
												<a href="javascript: void(0);" class="text-body fw-medium">#{{ blog.id }}</a>
											</td>
											<td>{{ blog.titre }}</td>
											<td  colspan="2">{{ blog.description }}</td>
                                            <td>{{ blog.publication }}</td>										
											<td>
												<a href="/dashboard/admin-blog/edit/{{blog.id}}" class="btn btn-primary btn-sm">Voir</a>
											</td>
											<td>
												<a href="/dashboard/admin-blog/delete/{{blog.id}}" class="btn btn-danger btn-sm">supprimer</a>
											</td>
										</tr>

									{% endfor %}


								</tbody>
							</table>
						</div>

					</div>
				</div>
		</div>
	</div>


{% endblock %}

templates/dashboard/dashboard.html.twig
{% extends "dashboard/_base.html.twig" %}

{% block injectedPage %}

	<!-- start page title -->
	<div class="row">
		<div class="col-12">
			<div class="page-title-box d-flex align-items-center justify-content-between">
				<h4 class="page-title mb-0 font-size-18">Tableau de bord</h4>
			</div>
		</div>
	</div>
	<!-- end page title -->

	<div class="row">
		<div class="col-xl-3">
			<div class="card">
				<div class="card-body">
					<div class="d-flex align-items-start">
						<div class="avatar-sm font-size-20 me-3">
							<span class="avatar-title bg-soft-primary text-primary rounded">
								<i class="mdi mdi-bank"></i>
							</span>
						</div>
						<div class="flex-1">
							<div class="font-size-16 mt-2">Stats Entreprise</div>
						</div>
					</div>
					<h4 class="mt-4">{{ count_entreprise }}</h4>
					<div class="row">
						<div class="col-7">
							<p class="mb-0">
								<span class="text-dark me-2">
									Demande{% if count_entreprise > 0 %}s{% endif %}
								</span>
							</p>
						</div>
						<div class="col-5 align-self-center">
							<div class="progress progress-sm">
								<div class="progress-bar bg-primary" role="progressbar" style="width: 62%" aria-valuenow="62" aria-valuemin="0" aria-valuemax="100"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="card">
				<div class="card-body">
					<div class="d-flex align-items-start">
						<div class="avatar-sm font-size-20 me-3">
							<span class="avatar-title bg-soft-primary text-primary rounded">
								<i class="mdi mdi-currency-usd"></i>
							</span>
						</div>
						<div class="flex-1">
							<div class="font-size-16 mt-2">Stat Comptabilité</div>

						</div>
					</div>
					<h4 class="mt-4">{{ count_comptabilite }}</h4>
					<div class="row">
						<div class="col-7">
							<p class="mb-0">
								<span class="text-dark me-2">
									Demande{% if count_comptabilite > 0 %}s{% endif %}
								</span>
							</p>
						</div>
						<div class="col-5 align-self-center">
							<div class="progress progress-sm">
								<div class="progress-bar bg-success" role="progressbar" style="width: 62%" aria-valuenow="62" aria-valuemin="0" aria-valuemax="100"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-xl-9">
			<div class="card">
				<div class="card-body">
					<h4 class="card-title mb-4">Les 4 dernières demandes (creation d'entreprise)</h4>

					<div class="table-responsive">
						<table class="table table-centered">
							<thead>
								<tr>
									<th scope="col">Id no.</th>
									<th scope="col">Noms & Prenoms</th>
									<th scope="col">Email</th>
									<th scope="col" colspan="2">Type/Entreprise</th>
								</tr>
							</thead>
							<tbody>
							{% for key, demande in entreprise %}	
										{% if  key < 4 %}	

											<tr>
												<td>
													<a href="javascript: void(0);" class="text-body fw-medium">#{{ demande.id }}</a>
												</td>
												<td>{{ demande.nom }} {{ demande.prenom }}</td>
												<td>{{ demande.Email }}</td>
												<td>
													<div>{{ demande.TypeEntreprise}}</div>
													<span class="badge badge-soft-success font-size-12">{{ demande.NomStructure}}</span>
												</td>
												<td>
													<a href="/dashboard/consultion-demandes-{{demande.id}}" class="btn btn-primary btn-sm">Voir</a>
												</td>
											</tr>

										{% endif %}
								
							{% endfor %}
								
								
							</tbody>
						</table>
					</div>

				</div>
			</div>

			<br>

			<div class="card">
				<div class="card-body">
					<h4 class="card-title mb-4">Les 4 dernières demandes (déleguer ma Comptabilité)</h4>

					<div class="table-responsive">
						<table class="table table-centered">
							<thead>
								<tr>
									<th scope="col">Id no.</th>
									<th scope="col">Noms & Prenoms</th>
									<th scope="col">Email</th>
									<th scope="col" colspan="4">Abonnement/Prix</th>
								</tr>
							</thead>
							<tbody>
							{% for key, demande in comptabilite %}	
										{% if  key < 4 %}	

											<tr>
												<td>
													<a href="javascript: void(0);" class="text-body fw-medium">#{{ demande.id }}</a>
												</td>
												<td>{{ demande.nom }} {{ demande.prenom }}</td>
												<td>{{ demande.Email }}</td>
												<td>
													<div>{{ demande.TypeAbonnement}}</div>
													<span class="badge badge-soft-success font-size-12"> € {{ demande.Montant}}</span>
												</td>
												<td>
													<a href="/dashboard/consultion-demandes-{{demande.id}}" class="btn btn-primary btn-sm">Voir</a>
												</td>
											</tr>

										{% endif %}
								
							{% endfor %}
								
								
							</tbody>
						</table>
					</div>
					
				</div>
			</div>
		</div>


	</div>
	<!-- end row -->


{% endblock %}

templates/dashboard/demandes.html.twig
{% extends "dashboard/_base.html.twig" %}

{% block injectedPage %}

	<!-- start page title -->
	<div class="row">
		<div class="col-12">
			<div class="page-title-box d-flex align-items-center justify-content-between">
				<h4 class="page-title mb-0 font-size-18">Consulation</h4>
			</div>
		</div>
	</div>
	<!-- end page title -->

	<div class="row">
		<div class="col-lg-8">
			<div class="card">
				<div class="card-body">
					<div class="invoice-title">
						<h4 class="float-end font-size-16">No. #
							{{demandes.id}}</h4>
						<div class="mb-4">
							<img src="#" alt="" height="20"/>
						</div>
					</div>
					<hr>
					<div class="row">
						<div class="col-6">
							<strong>
								<address>

									Nom & Prenoms :<br>
									Email :
									<br>
									Mobile :
									<br>
									Structure :
									<br>
									Type :
									<br>
									{% if demandes.EntrepriseOrCompta == 2 %}
										Formule :
										<br>
									{% endif %}
								</address>
							</strong>
						</div>
						<div class="col-6 text-end">
							<address>

								{{ demandes.nom}}
								{{ demandes.prenom}}<br>
								{{ demandes.Email}}<br>
								{{ demandes.Mobile}}<br>
								{{ demandes.Structure}}<br>
								{{ demandes.TypeEntreprise}}<br>
								{% if demandes.EntrepriseOrCompta == 2 %}
									{{ demandes.Formule}}<br>
								{% endif %}
							</address>
						</div>
					</div>
					<div class="row">
						<div class="col-6 mt-3">
							<address>
								{% if demandes.EntrepriseOrCompta == 2 %}
									<strong>Montant</strong><br>
								{% endif %}
								<strong>Date</strong><br>

							</address>
						</div>
						<div class="col-6 mt-3 text-end">
							<address>

								{% if demandes.EntrepriseOrCompta == 2 %}
									<h2>€
										{{ demandes.Montant}}</h2>
								{% endif %}
								{{ demandes.DateCreation}}<br><br>
							</address>
						</div>
					</div>


					<div class="d-print-none">
						<div class="float-end">
							<a href="javascript:window.print()" class="btn btn-success waves-effect waves-light">
								<i class="fa fa-print"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-lg-4">
			<div class="card d-flex justify-content-center">
				{% if demandes.Status != "Repondu" %}
					<div class="col-lg-10 m-2 mb-5">
						<p class="pt-4">Reponse a la
							<span class="is-text-primary">demande</span>.</p>

						<textarea name="" cols="30" id="message-reponse" placeholder="Ecrivez votre message de reponse ici" class="form-control" rows="5"></textarea>

						<center id="loading-indicator" class="d-none">
							<img src="{{ asset('images/loader.svg')}}" width="100px">
						</center>

						<a class="btn btn-secondary my-3" href="#">Valider</a>

					</div>
				{% else %}
					<p class="alert alert-success my-3">Repondu</p>
				{% endif %}
			</div>
		</div>
	</div>

	<script>// ----------------------------------------------------------------------------
// reponse mail
// ----------------------------------------------------------------------------
</script>{% endblock %}

templates/dashboard/liste.html.twig
{% extends "dashboard/_base.html.twig" %}

{% block injectedPage %}

	<!-- start page title -->
	<div class="row">
		<div class="col-12">
			<div class="page-title-box d-flex align-items-center justify-content-between">
				<h4 class="page-title mb-0 font-size-18">Total # {{ demandes | length}}</h4>
			</div>
		</div>
	</div>
	<!-- end page title -->

	<div class="row">

		<div class="col-xl-12">
			{% if type == 1 %}
				<div class="card">
					<div class="card-body">
						<h4 class="card-title mb-4">Les demandes (creation d'entreprise)</h4>

						<div class="table-responsive">
							<table class="table table-centered">
								<thead>
									<tr>
										<th scope="col">Id no.</th>
										<th scope="col">Noms & Prenoms</th>
										<th scope="col">Email</th>
										<th scope="col" colspan="2">Type/Entreprise</th>
									</tr>
								</thead>
								<tbody>
									{% for demande in demandes %}


										<tr>
											<td>
												<a href="javascript: void(0);" class="text-body fw-medium">#{{ demande.id }}</a>
											</td>
											<td>{{ demande.nom }}
												{{ demande.prenom }}</td>
											<td>{{ demande.Email }}</td>
											<td>
												<div>{{ demande.TypeEntreprise}}</div>
												<span class="badge badge-soft-success font-size-12">{{ demande.NomStructure}}</span>
											</td>
											<td>
												<a href="/dashboard/consultion-demandes-{{demande.id}}" class="btn btn-primary btn-sm">Voir</a>
											</td>
										</tr>

									{% endfor %}


								</tbody>
							</table>
						</div>

					</div>
				</div>
			{% endif %}


			<br>

			{% if type ==2 %}
				<div class="card">
					<div class="card-body">
						<h4 class="card-title mb-4">Les demandes (déleguer ma Comptabilité)</h4>

						<div class="table-responsive">
							<table class="table table-centered">
								<thead>
									<tr>
										<th scope="col">Id no.</th>
										<th scope="col">Noms & Prenoms</th>
										<th scope="col">Email</th>
										<th scope="col" colspan="4">Abonnement/Prix</th>
									</tr>
								</thead>
								<tbody>
									{% for demande in demandes %}
									

											<tr>
												<td>
													<a href="javascript: void(0);" class="text-body fw-medium">#{{ demande.id }}</a>
												</td>
												<td>{{ demande.nom }}
													{{ demande.prenom }}</td>
												<td>{{ demande.Email }}</td>
												<td>
													<div>{{ demande.TypeAbonnement}}</div>
													<span class="badge badge-soft-success font-size-12">
														€
														{{ demande.Montant}}</span>
												</td>
												<td>
													<a href="/dashboard/consultion-demandes-{{demande.id}}" class="btn btn-primary btn-sm">Voir</a>
												</td>
											</tr>

								

									{% endfor %}


								</tbody>
							</table>
						</div>

					</div>
				</div>
			{% endif %}

		</div>


	</div>
	<!-- end row -->


{% endblock %}